# Generated by Django 2.2.1 on 2019-05-19 09:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classify', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '新闻分类',
                'db_table': 'classifies',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='image')),
            ],
            options={
                'verbose_name': '图片',
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='image')),
                ('img_desc', models.TextField()),
            ],
            options={
                'verbose_name': '新闻图片',
                'db_table': 'news_images',
            },
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subsidiary_name', models.CharField(max_length=20)),
                ('subsidiary_desc', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '子公司',
                'db_table': 'subsidiaries',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('video', models.FileField(upload_to='videos')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '视频',
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Classifies')),
            ],
            options={
                'verbose_name': '新闻',
                'db_table': 'news',
                'ordering': ['upload_time'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('good_name', models.CharField(max_length=100)),
                ('good_price', models.DecimalField(decimal_places=2, max_digits=4, max_length=5)),
                ('good_desc', ckeditor.fields.RichTextField()),
                ('good_img', models.URLField(max_length=100)),
                ('good_producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商品',
                'db_table': 'goods',
            },
        ),
    ]
